'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowLeft,Menu,Edit,CreditCard,List,Settings,LogOut} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {Shop} from '@/types';
import {Dialog} from '@/components/ui/Dialog';
import {Input,Textarea} from '@/components/ui/Input';
import {Button} from '@/components/ui/Button';
type Payment={id:string;purpose:string;amount_inr:number;status:string;created_at:string};
export function MerchantConsoleHeader({shop,onUpdated,onManage}:{shop?:Shop|null;onUpdated?:()=>void|Promise<void>;onManage?:()=>void}){
 const router=useRouter();const [menu,setMenu]=useState(false);const [panel,setPanel]=useState<'edit'|'payments'|null>(null);const [payments,setPayments]=useState<Payment[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [form,setForm]=useState({name:'',city:'',pincode:'',description:''});const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!menu)return;const dismiss=(event:PointerEvent)=>{if(!root.current?.contains(event.target as Node))setMenu(false);};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setMenu(false);};document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',escape);};},[menu]);
 const edit=()=>{setMenu(false);if(!shop){router.push('/auth/merchant-onboarding');return;}setForm({name:shop.name,city:shop.city||'',pincode:shop.pincode||'',description:shop.description||''});setError('');setPanel('edit');};
 const paymentLog=async()=>{setMenu(false);setPanel('payments');setBusy(true);setError('');try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw Error('Please sign in to view payments.');const {data,error:queryError}=await supabase.from('payment_transactions').select('id,purpose,amount_inr,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50);if(queryError)throw queryError;setPayments(data||[]);}catch(err){setError(err instanceof Error?err.message:'Could not load payment history.');}finally{setBusy(false);}};
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(!shop)return;setBusy(true);setError('');try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw Error('Please sign in.');const {error:updateError}=await supabase.from('shops').update({name:form.name.trim(),city:form.city.trim(),pincode:form.pincode,description:form.description.trim()||null}).eq('id',shop.id).eq('owner_id',user.id);if(updateError)throw updateError;setPanel(null);await onUpdated?.();}catch(err){setError(err instanceof Error?err.message:'Could not save shop details.');}finally{setBusy(false);}};
 const signOut=async()=>{setMenu(false);const {error:signOutError}=await supabase.auth.signOut();if(signOutError){setError(signOutError.message);setPanel('payments');return;}router.replace('/auth/onboarding');};
 return <><header className="merchant-console-header"><div className="merchant-console-inner"><button aria-label="Back to marketplace" onClick={()=>router.push('/home')}><ArrowLeft/></button><div><h1>Merchant Console</h1><p>Manage your store</p></div><div className="merchant-menu-root" ref={root}><button aria-label="Merchant menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu/></button>{menu&&<div className="merchant-console-menu"><button onClick={edit}><Edit/>Edit shop details</button><button onClick={()=>void paymentLog()}><CreditCard/>Payment log</button><button onClick={()=>{setMenu(false);if(shop)onManage?.();else router.push('/auth/merchant-onboarding');}}><List/>Manage listings</button><button onClick={()=>router.push('/settings')}><Settings/>Account settings</button><button onClick={()=>void signOut()}><LogOut/>Sign out</button></div>}</div></div></header><Dialog isOpen={panel!==null} onClose={()=>setPanel(null)} title={panel==='edit'?'Edit shop details':'Payment log'}>{error&&<p className="auth-error" role="alert">{error}</p>}{panel==='edit'?<form onSubmit={save} className="space-y-3"><Input label="Shop name" required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input label="City" required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><Input label="Pincode" required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={form.pincode} onChange={e=>setForm({...form,pincode:e.target.value.replace(/\D/g,'')})}/><Textarea label="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Button type="submit" className="w-full" disabled={busy}>{busy?'Saving...':'Save changes'}</Button></form>:busy?<p>Loading payments...</p>:!error&&payments.length===0?<p className="text-slate-600">No payments yet.</p>:<ul className="payment-log-list">{payments.map(payment=><li key={payment.id}><div><strong>{payment.purpose.replace(/_/g,' ')}</strong><span>{new Date(payment.created_at).toLocaleDateString('en-IN')}</span></div><div><strong>{'\u20b9'}{payment.amount_inr}</strong><span>{payment.status}</span></div></li>)}</ul>}</Dialog></>;
}
