'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Heart,MessageCircle,Share2,Volume2,VolumeX,RotateCw,Play} from 'lucide-react';
import {BottomNav} from '@/components/ui/BottomNav';
import {supabase} from '@/lib/supabase';
import {useRouter} from 'next/navigation';
type Reel={id:string;title:string;media_url:string;shop_id:string|null;target_url:string|null};
function ReelCard({reel}:{reel:Reel}){const router=useRouter();const video=useRef<HTMLVideoElement>(null);const card=useRef<HTMLElement>(null);const [muted,setMuted]=useState(true);const [liked,setLiked]=useState(false);const [paused,setPaused]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{const player=video.current;if(!player)return;if(entries[0].isIntersecting){player.play().then(()=>setPaused(false)).catch(()=>setPaused(true));}else{player.pause();setPaused(true);}},{threshold:0.65});if(card.current)observer.observe(card.current);return()=>observer.disconnect();},[]);
 const togglePlay=()=>{const player=video.current;if(!player)return;if(player.paused)player.play().then(()=>setPaused(false)).catch(()=>setError('Tap to retry playback.'));else{player.pause();setPaused(true);}};
 const share=async()=>{const url=reel.shop_id?window.location.origin+'/shop/'+reel.shop_id:window.location.origin+'/reels';try{if(navigator.share)await navigator.share({title:reel.title,url});else{await navigator.clipboard.writeText(url);setMessage('Link copied');}}catch(err){if(!(err instanceof DOMException&&err.name==='AbortError'))setMessage('Could not share this reel.');}};
 return <article className="reel-card" ref={card}><video ref={video} src={reel.media_url} muted={muted} loop playsInline preload="metadata" onError={()=>setError('This video could not be loaded.')} aria-label={reel.title}/><button className="reel-play-area" onClick={togglePlay} aria-label={paused?'Play reel':'Pause reel'}>{paused&&!error&&<Play/>}</button>{error&&<p className="reel-error" role="alert">{error}</p>}<div className="reel-actions"><button onClick={()=>setMuted(!muted)} aria-label={muted?'Unmute':'Mute'}>{muted?<VolumeX/>:<Volume2/>}</button><button onClick={()=>setLiked(!liked)} aria-label={liked?'Unlike reel':'Like reel'} aria-pressed={liked} className={liked?'liked':''}><Heart fill={liked?'currentColor':'none'}/></button><button aria-label="View shop" onClick={()=>router.push(reel.shop_id?'/shop/'+reel.shop_id:'/shops')}><MessageCircle/></button><button aria-label="Share reel" onClick={()=>void share()}><Share2/></button></div><div className="reel-caption"><button onClick={()=>router.push(reel.shop_id?'/shop/'+reel.shop_id:'/shops')}>{reel.title}</button>{message&&<p role="status">{message}</p>}</div></article>;
}
export default function ReelsScreen(){const [reels,setReels]=useState<Reel[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{const {data,error:queryError}=await supabase.from('advertisements').select('id,title,media_url,shop_id,target_url,starts_at,ends_at').eq('media_type','video').eq('is_active',true).eq('approval_status','approved').order('sort_order').limit(30);if(queryError)throw queryError;const now=Date.now();setReels((data||[]).filter(item=>item.media_url&&(!item.starts_at||Date.parse(item.starts_at)<=now)&&(!item.ends_at||Date.parse(item.ends_at)>=now)));}catch(err){setError(err instanceof Error?err.message:'Could not load reels.');}finally{setLoading(false);}},[]);useEffect(()=>{void Promise.resolve().then(load);},[load]);return <main className="reels-page"><button className="reels-refresh" aria-label="Refresh reels" onClick={()=>void load()}><RotateCw/></button>{loading?<div className="reels-empty">Loading reels...</div>:error?<div className="reels-empty"><p role="alert">{error}</p><button onClick={()=>void load()}>Try again</button></div>:reels.length?<div className="reels-feed">{reels.map(reel=><ReelCard key={reel.id} reel={reel}/>)}</div>:<div className="reels-empty"><Play/><h1>No reels yet</h1><p>Videos from local shops will appear here.</p></div>}<BottomNav/></main>;}
