'use client';
import {useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,CheckCircle2,Home,Info,Lock,Mail,ShoppingCart} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {Input} from '@/components/ui/Input';
export default function LoginScreen(){
 const router=useRouter();const [role,setRole]=useState<'customer'|'merchant'>('customer');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const login=async(event:React.FormEvent)=>{event.preventDefault();setError('');setLoading(true);try{const {data,error:loginError}=await supabase.auth.signInWithPassword({email,password});if(loginError)throw loginError;const {data:profile}=await supabase.from('profiles').select('role').eq('id',data.user.id).single();router.push(profile?.role==='admin'?'/admin/dashboard':role==='merchant'?'/merchant/store':'/home');}catch(err){setError(err instanceof Error?err.message:'Could not sign in. Please try again.');}finally{setLoading(false);}};
 const googleLogin=async()=>{setLoading(true);setError('');try{sessionStorage.setItem('pincodemart-login-role',role);const {error:googleError}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+'/'}});if(googleError)throw googleError;}catch(err){setError(err instanceof Error?err.message:'Google sign-in is unavailable.');}finally{setLoading(false);}};
 return <main className="reference-auth-page"><div className="reference-auth-intro"><button className="auth-back" aria-label="Back to onboarding" onClick={()=>router.push('/auth/onboarding')}><ArrowLeft/></button><div className="auth-brand"><Image src="/assets/logoc.png" alt="" width={35} height={35} priority/><strong>PincodeMart</strong></div><p className="auth-tagline">Your neighbourhood super-app</p><h1>Welcome back</h1><p>Sign in to continue shopping locally.</p><div className="auth-feature-pills"><span><ShoppingCart/>Shop Local</span><span><Home/>Rental Homes</span></div></div><section className="reference-auth-card"><div className="auth-grab-bar"/><h2>Sign in</h2><p className="auth-card-description">Choose how you want to sign in.</p><span className="auth-small-label">Login as</span><div className="auth-role-toggle">{(['customer','merchant'] as const).map(item=><button key={item} className={role===item?'active':''} aria-pressed={role===item} onClick={()=>setRole(item)}>{item==='customer'?'Customer':'Merchant'}</button>)}</div><p className="auth-create-link">New here? <Link href="/auth/signup">Create account</Link></p><button className="auth-google" disabled={loading} onClick={()=>void googleLogin()}><span aria-hidden="true">G</span>Continue with Google</button><div className="auth-divider"><span>or use email</span></div><form onSubmit={login} className="reference-auth-form">{error&&<p role="alert" className="auth-error">{error}</p>}<label htmlFor="login-email">Email</label><Input id="login-email" type="email" autoComplete="email" placeholder="Enter email" value={email} onChange={e=>setEmail(e.target.value)} required icon={<Mail size={16}/>}/><label htmlFor="login-password">Password</label><div className="auth-password"><Input id="login-password" type={showPassword?'text':'password'} autoComplete="current-password" placeholder="Enter password" value={password} onChange={e=>setPassword(e.target.value)} required icon={<Lock size={16}/>}/><button type="button" aria-label={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(!showPassword)}><Info size={17}/></button></div><button className="reference-primary auth-submit" type="submit" disabled={loading||!email||!password}>{loading?'Signing in...':'Sign in'}</button></form><div className="auth-trust"><span><Lock/>Secure</span><span><CheckCircle2/>Verified</span><span><Lock/>Private</span></div><p className="auth-disclaimer">This app provides information only. Further confirmation from your end is necessary before proceeding or making any deal.</p><p className="auth-agreement">By creating an account you agree to our</p><div className="auth-policy-links"><Link href="/legal#terms">Terms of Service</Link><span>and</span><Link href="/legal#privacy">Privacy Policy</Link></div></section></main>;
}
