'use client';
import { useRef, useState } from 'react';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { Home, Search, Send, ShoppingCart } from 'lucide-react';
const slides=[{title:['Shop Local,','Shop Smart'],description:'Discover thousands of neighbourhood stores, compare prices and get doorstep delivery in minutes',icon:ShoppingCart,tone:'shopping'},{title:['Rental Homes','Near You'],description:'Explore approved homes, tickets, and rides around your city or pincode.',icon:Home,tone:'rentals'},{title:['Courier,','Simplified'],description:'Send and receive parcels across the city. Track in real-time and never lose a package again.',icon:Send,tone:'courier'}];
export default function ReferenceOnboarding({onComplete}:{onComplete?:()=>void|Promise<void>}) {
 const router=useRouter(); const [index,setIndex]=useState(0);const [busy,setBusy]=useState(false);const touchStart=useRef<number|null>(null);const slide=slides[index];const Icon=slide.icon;
 const complete=async()=>{if(busy)return;setBusy(true);try{if(onComplete)await onComplete();else router.push('/auth/login');}finally{setBusy(false);}};
 return <main className={'reference-onboarding onboarding-'+slide.tone}><header className="onboarding-brand-row"><div className="onboarding-brand"><Image src="/assets/logoc.png" alt="" width={25} height={25} priority/><strong>PincodeMart</strong></div><button onClick={()=>void complete()} disabled={busy}>Skip</button></header><section className="onboarding-slide" key={index} onTouchStart={e=>{touchStart.current=e.touches[0].clientX;}} onTouchEnd={e=>{if(touchStart.current===null)return;const delta=touchStart.current-e.changedTouches[0].clientX;if(Math.abs(delta)>45)setIndex(v=>Math.max(0,Math.min(2,v+(delta>0?1:-1))));touchStart.current=null;}}><div className="onboarding-icon"><div><Icon aria-hidden="true"/></div></div><h1>{slide.title[0]}<br/>{slide.title[1]}</h1><p>{slide.description}</p><ul className="onboarding-benefits">{index<2&&<li><Search/>Fastest discovery of products</li>}<li><ShoppingCart/>500+ local shops online</li>{index===2&&<><li><Send/>Reach anywhere in 3 minutes</li><li><Send/>Same-day delivery available</li></>}</ul></section><footer className="onboarding-footer"><div className="onboarding-dots" aria-label="Onboarding slides">{slides.map((item,i)=><button key={item.tone} className={i===index?'active':''} aria-label={'Slide '+(i+1)} aria-current={i===index?'step':undefined} onClick={()=>setIndex(i)}/>)}</div><button className="reference-primary" disabled={busy} onClick={()=>index<2?setIndex(index+1):void complete()}>{busy?'Please wait...':index<2?'Next':onComplete?'Get started':'Login with Email'}</button>{!onComplete&&<button className="onboarding-create" onClick={()=>router.push('/auth/signup')}>Create New Account</button>}<p>Free to join &middot; No hidden fees</p></footer></main>;
}
